CREATE USER movies_usr IDENTIFIED BY oracle;

GRANT CONNECT, RESOURCE, DBA TO movies_usr;

CREATE TABLE MOVIES (
  MOVIEID INTEGER NOT NULL PRIMARY KEY,
  MOVIENAME VARCHAR(255),
  YEAR INTEGER,
  STUDIO VARCHAR(255),
  GENERE VARCHAR(255),
  RATING VARCHAR(255),
  RUNTIME INTEGER,
  DIRECTOR VARCHAR(255),
  MOVIEDESCRIPTION VARCHAR(2048)
);

CREATE TABLE REVIEWS (
  REVIEWID INTEGER NOT NULL PRIMARY KEY,
  MOVIEID INTEGER NOT NULL,
  REVIEWERNAME VARCHAR(255),
  SCORE INTEGER NOT NULL,
  REVIEWDATE VARCHAR(255),
  REVIEWDESCRIPTION VARCHAR(2048)
);

CREATE SEQUENCE MOVIES_SEQ
 START WITH 100
 INCREMENT BY 1;
 
CREATE SEQUENCE REVIEWS_SEQ
 START WITH 1000
 INCREMENT BY 1;
 
INSERT INTO MOVIES(MOVIEID, MOVIENAME, YEAR, STUDIO, GENERE, RATING, RUNTIME, DIRECTOR, MOVIEDESCRIPTION) 
VALUES (MOVIES_SEQ.NEXTVAL, 'name1',2006, 'studio1', 'genre1', 'rating1', 120, 'director1', 'description1');

INSERT INTO MOVIES(MOVIEID, MOVIENAME, YEAR, STUDIO, GENERE, RATING, RUNTIME, DIRECTOR, MOVIEDESCRIPTION) 
VALUES (MOVIES_SEQ.NEXTVAL, 'name2',2007, 'studio2', 'genre2', 'rating2', 120, 'director2', 'description2');

INSERT INTO MOVIES(MOVIEID, MOVIENAME, YEAR, STUDIO, GENERE, RATING, RUNTIME, DIRECTOR, MOVIEDESCRIPTION) 
VALUES (MOVIES_SEQ.NEXTVAL, 'name3',2008, 'studio3', 'genre3', 'rating3', 120, 'director3', 'description3');


INSERT INTO REVIEWS(REVIEWID, MOVIEID, REVIEWERNAME, SCORE,REVIEWDATE, REVIEWDESCRIPTION)
VALUES (REVIEWS_SEQ.NEXTVAL, 100, 'name1', 4, 'date1', 'description1');

INSERT INTO REVIEWS(REVIEWID, MOVIEID, REVIEWERNAME, SCORE,REVIEWDATE, REVIEWDESCRIPTION)
VALUES (REVIEWS_SEQ.NEXTVAL, 100, 'name2', 4, 'date2', 'description2');

INSERT INTO REVIEWS(REVIEWID, MOVIEID, REVIEWERNAME, SCORE,REVIEWDATE, REVIEWDESCRIPTION)
VALUES (REVIEWS_SEQ.NEXTVAL, 100, 'name3', 4, 'date3', 'description3');

INSERT INTO REVIEWS(REVIEWID, MOVIEID, REVIEWERNAME, SCORE,REVIEWDATE, REVIEWDESCRIPTION)
VALUES (REVIEWS_SEQ.NEXTVAL, 101, 'name4', 4, 'date4', 'description4');

INSERT INTO REVIEWS(REVIEWID, MOVIEID, REVIEWERNAME, SCORE,REVIEWDATE, REVIEWDESCRIPTION)
VALUES (REVIEWS_SEQ.NEXTVAL, 101, 'name5', 4, 'date5', 'description5');

INSERT INTO REVIEWS(REVIEWID, MOVIEID, REVIEWERNAME, SCORE,REVIEWDATE, REVIEWDESCRIPTION)
VALUES (REVIEWS_SEQ.NEXTVAL, 101, 'name6', 4, 'date6', 'description6');

INSERT INTO REVIEWS(REVIEWID, MOVIEID, REVIEWERNAME, SCORE,REVIEWDATE, REVIEWDESCRIPTION)
VALUES (REVIEWS_SEQ.NEXTVAL, 102, 'name7', 4, 'date7', 'description7');

INSERT INTO REVIEWS(REVIEWID, MOVIEID, REVIEWERNAME, SCORE,REVIEWDATE, REVIEWDESCRIPTION)
VALUES (REVIEWS_SEQ.NEXTVAL, 102, 'name8', 4, 'date8', 'description8');

INSERT INTO REVIEWS(REVIEWID, MOVIEID, REVIEWERNAME, SCORE,REVIEWDATE, REVIEWDESCRIPTION)
VALUES (REVIEWS_SEQ.NEXTVAL, 102, 'name9', 4, 'date9', 'description9');

COMMIT;
